services:
  - name: gitlab.udevs.io:5050/docker/docker:dind
    alias: docker

before_script:
  ## docker login
  - docker login $CI_REGISTRY --username $CI_REGISTRY_USER --password $CI_REGISTRY_PASSWORD
  ## install dependencies
  - apk update && apk --no-cache --update add build-base openssh curl

stages:
  - build
  - migrate
  - deploy

build-image:
  stage: build
  script:
    - make build-image REGISTRY=$CI_REGISTRY PROJECT_NAMESPACE=$CI_PROJECT_NAMESPACE PROJECT_NAME=$CI_PROJECT_NAME TAG=$CI_PIPELINE_IID
    - make push-image REGISTRY=$CI_REGISTRY PROJECT_NAMESPACE=$CI_PROJECT_NAMESPACE PROJECT_NAME=$CI_PROJECT_NAME TAG=$CI_PIPELINE_IID
  only:
    - master

migaret-prod:
  stage: migarte
  before_script:
    - apk add wget && wget https://github.com/golang-migrate/migrate/releases/download/v4.14.1/migrate.linux-amd64.tar.gz
    - tar -xvf migrate.linux-amd64.tar.gz && mv migrate.linux-amd64 migrate && chmod +x migrate
  script:
    - ./migrate -path=$PWD/migrations -database="${URECRUIT_PROD_USERDB}?sslmode=disable&x-migrations-table=migrations_$CI_PROJECT_NAME" up
  only:
    - master

deploy-prod:
  stage: deploy
  before_script:
    - eval $(ssh-agent -s)
    - echo "$GITLAB_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - ssh -o StrictHostKeyChecking=no $URECRUIT_PROD_USER@$URECRUIT_PROD_HOST 'docker service update --with-registry-auth
      --image '$CI_REGISTRY'/'$CI_PROJECT_NAMESPACE'/'$CI_PROJECT_NAME':'$CI_PIPELINE_IID' '$CI_PROJECT_NAME''
  only:
    - master