// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: researcher.proto

package user_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Researcher struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string       `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email           string       `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phone           string       `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	ProfessionTitle string       `protobuf:"bytes,5,opt,name=profession_title,json=professionTitle,proto3" json:"profession_title,omitempty"`
	RoleId          string       `protobuf:"bytes,6,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	CompanyId       string       `protobuf:"bytes,7,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	Photo           string       `protobuf:"bytes,8,opt,name=photo,proto3" json:"photo,omitempty"`
	CompanyName     *CompanyName `protobuf:"bytes,9,opt,name=company_name,json=companyName,proto3" json:"company_name,omitempty"`
}

func (x *Researcher) Reset() {
	*x = Researcher{}
	if protoimpl.UnsafeEnabled {
		mi := &file_researcher_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Researcher) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Researcher) ProtoMessage() {}

func (x *Researcher) ProtoReflect() protoreflect.Message {
	mi := &file_researcher_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Researcher.ProtoReflect.Descriptor instead.
func (*Researcher) Descriptor() ([]byte, []int) {
	return file_researcher_proto_rawDescGZIP(), []int{0}
}

func (x *Researcher) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Researcher) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Researcher) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Researcher) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Researcher) GetProfessionTitle() string {
	if x != nil {
		return x.ProfessionTitle
	}
	return ""
}

func (x *Researcher) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *Researcher) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *Researcher) GetPhoto() string {
	if x != nil {
		return x.Photo
	}
	return ""
}

func (x *Researcher) GetCompanyName() *CompanyName {
	if x != nil {
		return x.CompanyName
	}
	return nil
}

type GetAllResearcherResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Researchers []*Researcher `protobuf:"bytes,1,rep,name=researchers,proto3" json:"researchers,omitempty"`
	Count       int32         `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *GetAllResearcherResponse) Reset() {
	*x = GetAllResearcherResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_researcher_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllResearcherResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllResearcherResponse) ProtoMessage() {}

func (x *GetAllResearcherResponse) ProtoReflect() protoreflect.Message {
	mi := &file_researcher_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllResearcherResponse.ProtoReflect.Descriptor instead.
func (*GetAllResearcherResponse) Descriptor() ([]byte, []int) {
	return file_researcher_proto_rawDescGZIP(), []int{1}
}

func (x *GetAllResearcherResponse) GetResearchers() []*Researcher {
	if x != nil {
		return x.Researchers
	}
	return nil
}

func (x *GetAllResearcherResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ResearcherId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ResearcherId) Reset() {
	*x = ResearcherId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_researcher_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResearcherId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResearcherId) ProtoMessage() {}

func (x *ResearcherId) ProtoReflect() protoreflect.Message {
	mi := &file_researcher_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResearcherId.ProtoReflect.Descriptor instead.
func (*ResearcherId) Descriptor() ([]byte, []int) {
	return file_researcher_proto_rawDescGZIP(), []int{2}
}

func (x *ResearcherId) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateResearcherPhoto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Photo  string `protobuf:"bytes,2,opt,name=photo,proto3" json:"photo,omitempty"`
}

func (x *UpdateResearcherPhoto) Reset() {
	*x = UpdateResearcherPhoto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_researcher_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateResearcherPhoto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResearcherPhoto) ProtoMessage() {}

func (x *UpdateResearcherPhoto) ProtoReflect() protoreflect.Message {
	mi := &file_researcher_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResearcherPhoto.ProtoReflect.Descriptor instead.
func (*UpdateResearcherPhoto) Descriptor() ([]byte, []int) {
	return file_researcher_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateResearcherPhoto) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateResearcherPhoto) GetPhoto() string {
	if x != nil {
		return x.Photo
	}
	return ""
}

type CompanyName struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *CompanyName) Reset() {
	*x = CompanyName{}
	if protoimpl.UnsafeEnabled {
		mi := &file_researcher_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompanyName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompanyName) ProtoMessage() {}

func (x *CompanyName) ProtoReflect() protoreflect.Message {
	mi := &file_researcher_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompanyName.ProtoReflect.Descriptor instead.
func (*CompanyName) Descriptor() ([]byte, []int) {
	return file_researcher_proto_rawDescGZIP(), []int{4}
}

func (x *CompanyName) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CompanyName) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_researcher_proto protoreflect.FileDescriptor

var file_researcher_proto_rawDesc = []byte{
	0x0a, 0x10, 0x72, 0x65, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x08, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8f, 0x02, 0x0a,
	0x0a, 0x52, 0x65, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x29, 0x0a, 0x10, 0x70,
	0x72, 0x6f, 0x66, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x70, 0x72, 0x6f, 0x66, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x12,
	0x1d, 0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x49, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70,
	0x68, 0x6f, 0x74, 0x6f, 0x12, 0x38, 0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x67, 0x65, 0x6e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x4e, 0x61, 0x6d,
	0x65, 0x52, 0x0b, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x68,
	0x0a, 0x18, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x0b, 0x72, 0x65,
	0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x65, 0x72, 0x52, 0x0b, 0x72, 0x65, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x65,
	0x72, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x1e, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x65, 0x72, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x46, 0x0a, 0x15, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x65, 0x72, 0x50, 0x68, 0x6f, 0x74,
	0x6f, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68,
	0x6f, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x74, 0x6f,
	0x22, 0x31, 0x0a, 0x0b, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x42, 0x17, 0x5a, 0x15, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_researcher_proto_rawDescOnce sync.Once
	file_researcher_proto_rawDescData = file_researcher_proto_rawDesc
)

func file_researcher_proto_rawDescGZIP() []byte {
	file_researcher_proto_rawDescOnce.Do(func() {
		file_researcher_proto_rawDescData = protoimpl.X.CompressGZIP(file_researcher_proto_rawDescData)
	})
	return file_researcher_proto_rawDescData
}

var file_researcher_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_researcher_proto_goTypes = []interface{}{
	(*Researcher)(nil),               // 0: genproto.Researcher
	(*GetAllResearcherResponse)(nil), // 1: genproto.GetAllResearcherResponse
	(*ResearcherId)(nil),             // 2: genproto.ResearcherId
	(*UpdateResearcherPhoto)(nil),    // 3: genproto.UpdateResearcherPhoto
	(*CompanyName)(nil),              // 4: genproto.CompanyName
}
var file_researcher_proto_depIdxs = []int32{
	4, // 0: genproto.Researcher.company_name:type_name -> genproto.CompanyName
	0, // 1: genproto.GetAllResearcherResponse.researchers:type_name -> genproto.Researcher
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_researcher_proto_init() }
func file_researcher_proto_init() {
	if File_researcher_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_researcher_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Researcher); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_researcher_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllResearcherResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_researcher_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResearcherId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_researcher_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateResearcherPhoto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_researcher_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompanyName); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_researcher_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_researcher_proto_goTypes,
		DependencyIndexes: file_researcher_proto_depIdxs,
		MessageInfos:      file_researcher_proto_msgTypes,
	}.Build()
	File_researcher_proto = out.File
	file_researcher_proto_rawDesc = nil
	file_researcher_proto_goTypes = nil
	file_researcher_proto_depIdxs = nil
}
