// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package user_service

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Admin struct {
	Id                   string        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AccessToken          string        `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	Name                 string        `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Username             string        `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Password             string        `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	Phone                string        `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"`
	Active               bool          `protobuf:"varint,7,opt,name=active,proto3" json:"active,omitempty"`
	CreatedAt            string        `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string        `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Permissions          []*Permission `protobuf:"bytes,13,rep,name=permissions,proto3" json:"permissions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Admin) Reset()         { *m = Admin{} }
func (m *Admin) String() string { return proto.CompactTextString(m) }
func (*Admin) ProtoMessage()    {}
func (*Admin) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *Admin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Admin.Unmarshal(m, b)
}
func (m *Admin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Admin.Marshal(b, m, deterministic)
}
func (m *Admin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Admin.Merge(m, src)
}
func (m *Admin) XXX_Size() int {
	return xxx_messageInfo_Admin.Size(m)
}
func (m *Admin) XXX_DiscardUnknown() {
	xxx_messageInfo_Admin.DiscardUnknown(m)
}

var xxx_messageInfo_Admin proto.InternalMessageInfo

func (m *Admin) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Admin) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *Admin) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Admin) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Admin) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Admin) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *Admin) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *Admin) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Admin) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *Admin) GetPermissions() []*Permission {
	if m != nil {
		return m.Permissions
	}
	return nil
}

type Customer struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AccessToken          string   `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Lastname             string   `protobuf:"bytes,4,opt,name=lastname,proto3" json:"lastname,omitempty"`
	Password             string   `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	Phone                string   `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"`
	Active               bool     `protobuf:"varint,7,opt,name=active,proto3" json:"active,omitempty"`
	PhoneVerified        bool     `protobuf:"varint,8,opt,name=phone_verified,json=phoneVerified,proto3" json:"phone_verified,omitempty"`
	Address              string   `protobuf:"bytes,9,opt,name=address,proto3" json:"address,omitempty"`
	Gender               string   `protobuf:"bytes,10,opt,name=gender,proto3" json:"gender,omitempty"`
	DateOfBirth          string   `protobuf:"bytes,11,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	Avatar               string   `protobuf:"bytes,12,opt,name=avatar,proto3" json:"avatar,omitempty"`
	GoogleId             string   `protobuf:"bytes,13,opt,name=google_id,json=googleId,proto3" json:"google_id,omitempty"`
	FacebookId           string   `protobuf:"bytes,14,opt,name=facebook_id,json=facebookId,proto3" json:"facebook_id,omitempty"`
	AppleId              string   `protobuf:"bytes,15,opt,name=apple_id,json=appleId,proto3" json:"apple_id,omitempty"`
	CreatedAt            string   `protobuf:"bytes,16,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,17,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt            string   `protobuf:"bytes,18,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	FcmToken             string   `protobuf:"bytes,19,opt,name=fcm_token,json=fcmToken,proto3" json:"fcm_token,omitempty"`
	Platform             int32    `protobuf:"varint,20,opt,name=platform,proto3" json:"platform,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Customer) Reset()         { *m = Customer{} }
func (m *Customer) String() string { return proto.CompactTextString(m) }
func (*Customer) ProtoMessage()    {}
func (*Customer) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *Customer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Customer.Unmarshal(m, b)
}
func (m *Customer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Customer.Marshal(b, m, deterministic)
}
func (m *Customer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Customer.Merge(m, src)
}
func (m *Customer) XXX_Size() int {
	return xxx_messageInfo_Customer.Size(m)
}
func (m *Customer) XXX_DiscardUnknown() {
	xxx_messageInfo_Customer.DiscardUnknown(m)
}

var xxx_messageInfo_Customer proto.InternalMessageInfo

func (m *Customer) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Customer) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *Customer) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Customer) GetLastname() string {
	if m != nil {
		return m.Lastname
	}
	return ""
}

func (m *Customer) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Customer) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *Customer) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *Customer) GetPhoneVerified() bool {
	if m != nil {
		return m.PhoneVerified
	}
	return false
}

func (m *Customer) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Customer) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *Customer) GetDateOfBirth() string {
	if m != nil {
		return m.DateOfBirth
	}
	return ""
}

func (m *Customer) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *Customer) GetGoogleId() string {
	if m != nil {
		return m.GoogleId
	}
	return ""
}

func (m *Customer) GetFacebookId() string {
	if m != nil {
		return m.FacebookId
	}
	return ""
}

func (m *Customer) GetAppleId() string {
	if m != nil {
		return m.AppleId
	}
	return ""
}

func (m *Customer) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Customer) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *Customer) GetDeletedAt() string {
	if m != nil {
		return m.DeletedAt
	}
	return ""
}

func (m *Customer) GetFcmToken() string {
	if m != nil {
		return m.FcmToken
	}
	return ""
}

func (m *Customer) GetPlatform() int32 {
	if m != nil {
		return m.Platform
	}
	return 0
}

type UserActivity struct {
	Id                   string             `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	User                 *UserActivity_User `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Element              string             `protobuf:"bytes,3,opt,name=element,proto3" json:"element,omitempty"`
	ElementId            string             `protobuf:"bytes,4,opt,name=element_id,json=elementId,proto3" json:"element_id,omitempty"`
	Action               string             `protobuf:"bytes,5,opt,name=action,proto3" json:"action,omitempty"`
	FromValue            string             `protobuf:"bytes,6,opt,name=from_value,json=fromValue,proto3" json:"from_value,omitempty"`
	ToValue              string             `protobuf:"bytes,7,opt,name=to_value,json=toValue,proto3" json:"to_value,omitempty"`
	Time                 string             `protobuf:"bytes,8,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *UserActivity) Reset()         { *m = UserActivity{} }
func (m *UserActivity) String() string { return proto.CompactTextString(m) }
func (*UserActivity) ProtoMessage()    {}
func (*UserActivity) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *UserActivity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserActivity.Unmarshal(m, b)
}
func (m *UserActivity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserActivity.Marshal(b, m, deterministic)
}
func (m *UserActivity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserActivity.Merge(m, src)
}
func (m *UserActivity) XXX_Size() int {
	return xxx_messageInfo_UserActivity.Size(m)
}
func (m *UserActivity) XXX_DiscardUnknown() {
	xxx_messageInfo_UserActivity.DiscardUnknown(m)
}

var xxx_messageInfo_UserActivity proto.InternalMessageInfo

func (m *UserActivity) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UserActivity) GetUser() *UserActivity_User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *UserActivity) GetElement() string {
	if m != nil {
		return m.Element
	}
	return ""
}

func (m *UserActivity) GetElementId() string {
	if m != nil {
		return m.ElementId
	}
	return ""
}

func (m *UserActivity) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *UserActivity) GetFromValue() string {
	if m != nil {
		return m.FromValue
	}
	return ""
}

func (m *UserActivity) GetToValue() string {
	if m != nil {
		return m.ToValue
	}
	return ""
}

func (m *UserActivity) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

type UserActivity_User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Username             string   `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Phone                string   `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserActivity_User) Reset()         { *m = UserActivity_User{} }
func (m *UserActivity_User) String() string { return proto.CompactTextString(m) }
func (*UserActivity_User) ProtoMessage()    {}
func (*UserActivity_User) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2, 0}
}

func (m *UserActivity_User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserActivity_User.Unmarshal(m, b)
}
func (m *UserActivity_User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserActivity_User.Marshal(b, m, deterministic)
}
func (m *UserActivity_User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserActivity_User.Merge(m, src)
}
func (m *UserActivity_User) XXX_Size() int {
	return xxx_messageInfo_UserActivity_User.Size(m)
}
func (m *UserActivity_User) XXX_DiscardUnknown() {
	xxx_messageInfo_UserActivity_User.DiscardUnknown(m)
}

var xxx_messageInfo_UserActivity_User proto.InternalMessageInfo

func (m *UserActivity_User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UserActivity_User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserActivity_User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserActivity_User) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type Permission struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Id                   string   `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Permission) Reset()         { *m = Permission{} }
func (m *Permission) String() string { return proto.CompactTextString(m) }
func (*Permission) ProtoMessage()    {}
func (*Permission) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *Permission) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Permission.Unmarshal(m, b)
}
func (m *Permission) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Permission.Marshal(b, m, deterministic)
}
func (m *Permission) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Permission.Merge(m, src)
}
func (m *Permission) XXX_Size() int {
	return xxx_messageInfo_Permission.Size(m)
}
func (m *Permission) XXX_DiscardUnknown() {
	xxx_messageInfo_Permission.DiscardUnknown(m)
}

var xxx_messageInfo_Permission proto.InternalMessageInfo

func (m *Permission) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Permission) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Permission) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{5}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type ListRequest struct {
	Search               string   `protobuf:"bytes,1,opt,name=search,proto3" json:"search,omitempty"`
	Limit                int32    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Page                 int32    `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{6}
}

func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (m *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(m, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

func (m *ListRequest) GetSearch() string {
	if m != nil {
		return m.Search
	}
	return ""
}

func (m *ListRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

//  This is for CreateRole message
type IdMessage struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IdMessage) Reset()         { *m = IdMessage{} }
func (m *IdMessage) String() string { return proto.CompactTextString(m) }
func (*IdMessage) ProtoMessage()    {}
func (*IdMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{7}
}

func (m *IdMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdMessage.Unmarshal(m, b)
}
func (m *IdMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdMessage.Marshal(b, m, deterministic)
}
func (m *IdMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdMessage.Merge(m, src)
}
func (m *IdMessage) XXX_Size() int {
	return xxx_messageInfo_IdMessage.Size(m)
}
func (m *IdMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_IdMessage.DiscardUnknown(m)
}

var xxx_messageInfo_IdMessage proto.InternalMessageInfo

func (m *IdMessage) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Role struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	ControlMovieCreators bool     `protobuf:"varint,3,opt,name=control_movie_creators,json=controlMovieCreators,proto3" json:"control_movie_creators,omitempty"`
	ControlCategory      bool     `protobuf:"varint,4,opt,name=control_category,json=controlCategory,proto3" json:"control_category,omitempty"`
	ControlFavoriteMovie bool     `protobuf:"varint,5,opt,name=control_favorite_movie,json=controlFavoriteMovie,proto3" json:"control_favorite_movie,omitempty"`
	ControlDashboard     bool     `protobuf:"varint,6,opt,name=control_dashboard,json=controlDashboard,proto3" json:"control_dashboard,omitempty"`
	ControlTariff        bool     `protobuf:"varint,7,opt,name=control_tariff,json=controlTariff,proto3" json:"control_tariff,omitempty"`
	ControlPermissions   bool     `protobuf:"varint,8,opt,name=control_permissions,json=controlPermissions,proto3" json:"control_permissions,omitempty"`
	ControlMovie         bool     `protobuf:"varint,9,opt,name=control_movie,json=controlMovie,proto3" json:"control_movie,omitempty"`
	ControlNotification  bool     `protobuf:"varint,10,opt,name=control_notification,json=controlNotification,proto3" json:"control_notification,omitempty"`
	ControlAdmin         bool     `protobuf:"varint,11,opt,name=control_admin,json=controlAdmin,proto3" json:"control_admin,omitempty"`
	ControlGenre         bool     `protobuf:"varint,12,opt,name=control_genre,json=controlGenre,proto3" json:"control_genre,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Role) Reset()         { *m = Role{} }
func (m *Role) String() string { return proto.CompactTextString(m) }
func (*Role) ProtoMessage()    {}
func (*Role) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{8}
}

func (m *Role) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Role.Unmarshal(m, b)
}
func (m *Role) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Role.Marshal(b, m, deterministic)
}
func (m *Role) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Role.Merge(m, src)
}
func (m *Role) XXX_Size() int {
	return xxx_messageInfo_Role.Size(m)
}
func (m *Role) XXX_DiscardUnknown() {
	xxx_messageInfo_Role.DiscardUnknown(m)
}

var xxx_messageInfo_Role proto.InternalMessageInfo

func (m *Role) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Role) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Role) GetControlMovieCreators() bool {
	if m != nil {
		return m.ControlMovieCreators
	}
	return false
}

func (m *Role) GetControlCategory() bool {
	if m != nil {
		return m.ControlCategory
	}
	return false
}

func (m *Role) GetControlFavoriteMovie() bool {
	if m != nil {
		return m.ControlFavoriteMovie
	}
	return false
}

func (m *Role) GetControlDashboard() bool {
	if m != nil {
		return m.ControlDashboard
	}
	return false
}

func (m *Role) GetControlTariff() bool {
	if m != nil {
		return m.ControlTariff
	}
	return false
}

func (m *Role) GetControlPermissions() bool {
	if m != nil {
		return m.ControlPermissions
	}
	return false
}

func (m *Role) GetControlMovie() bool {
	if m != nil {
		return m.ControlMovie
	}
	return false
}

func (m *Role) GetControlNotification() bool {
	if m != nil {
		return m.ControlNotification
	}
	return false
}

func (m *Role) GetControlAdmin() bool {
	if m != nil {
		return m.ControlAdmin
	}
	return false
}

func (m *Role) GetControlGenre() bool {
	if m != nil {
		return m.ControlGenre
	}
	return false
}

// // This is for GetAll code
type RoleListRequestId struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoleListRequestId) Reset()         { *m = RoleListRequestId{} }
func (m *RoleListRequestId) String() string { return proto.CompactTextString(m) }
func (*RoleListRequestId) ProtoMessage()    {}
func (*RoleListRequestId) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{9}
}

func (m *RoleListRequestId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleListRequestId.Unmarshal(m, b)
}
func (m *RoleListRequestId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleListRequestId.Marshal(b, m, deterministic)
}
func (m *RoleListRequestId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleListRequestId.Merge(m, src)
}
func (m *RoleListRequestId) XXX_Size() int {
	return xxx_messageInfo_RoleListRequestId.Size(m)
}
func (m *RoleListRequestId) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleListRequestId.DiscardUnknown(m)
}

var xxx_messageInfo_RoleListRequestId proto.InternalMessageInfo

func (m *RoleListRequestId) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// This is for GetId code
type GetRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{10}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	ControlMovieCreators bool     `protobuf:"varint,3,opt,name=control_movie_creators,json=controlMovieCreators,proto3" json:"control_movie_creators,omitempty"`
	ControlCategory      bool     `protobuf:"varint,4,opt,name=control_category,json=controlCategory,proto3" json:"control_category,omitempty"`
	ControlFavoriteMovie bool     `protobuf:"varint,5,opt,name=control_favorite_movie,json=controlFavoriteMovie,proto3" json:"control_favorite_movie,omitempty"`
	ControlDashboard     bool     `protobuf:"varint,6,opt,name=control_dashboard,json=controlDashboard,proto3" json:"control_dashboard,omitempty"`
	ControlTariff        bool     `protobuf:"varint,7,opt,name=control_tariff,json=controlTariff,proto3" json:"control_tariff,omitempty"`
	ControlPermissions   bool     `protobuf:"varint,8,opt,name=control_permissions,json=controlPermissions,proto3" json:"control_permissions,omitempty"`
	ControlMovie         bool     `protobuf:"varint,9,opt,name=control_movie,json=controlMovie,proto3" json:"control_movie,omitempty"`
	ControlNotification  bool     `protobuf:"varint,10,opt,name=control_notification,json=controlNotification,proto3" json:"control_notification,omitempty"`
	ControlAdmin         bool     `protobuf:"varint,11,opt,name=control_admin,json=controlAdmin,proto3" json:"control_admin,omitempty"`
	ControlGenre         bool     `protobuf:"varint,12,opt,name=control_genre,json=controlGenre,proto3" json:"control_genre,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{11}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetResponse) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *GetResponse) GetControlMovieCreators() bool {
	if m != nil {
		return m.ControlMovieCreators
	}
	return false
}

func (m *GetResponse) GetControlCategory() bool {
	if m != nil {
		return m.ControlCategory
	}
	return false
}

func (m *GetResponse) GetControlFavoriteMovie() bool {
	if m != nil {
		return m.ControlFavoriteMovie
	}
	return false
}

func (m *GetResponse) GetControlDashboard() bool {
	if m != nil {
		return m.ControlDashboard
	}
	return false
}

func (m *GetResponse) GetControlTariff() bool {
	if m != nil {
		return m.ControlTariff
	}
	return false
}

func (m *GetResponse) GetControlPermissions() bool {
	if m != nil {
		return m.ControlPermissions
	}
	return false
}

func (m *GetResponse) GetControlMovie() bool {
	if m != nil {
		return m.ControlMovie
	}
	return false
}

func (m *GetResponse) GetControlNotification() bool {
	if m != nil {
		return m.ControlNotification
	}
	return false
}

func (m *GetResponse) GetControlAdmin() bool {
	if m != nil {
		return m.ControlAdmin
	}
	return false
}

func (m *GetResponse) GetControlGenre() bool {
	if m != nil {
		return m.ControlGenre
	}
	return false
}

// This is for Update code
type UpdateList struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	ControlMovieCreators bool     `protobuf:"varint,3,opt,name=control_movie_creators,json=controlMovieCreators,proto3" json:"control_movie_creators,omitempty"`
	ControlCategory      bool     `protobuf:"varint,4,opt,name=control_category,json=controlCategory,proto3" json:"control_category,omitempty"`
	ControlFavoriteMovie bool     `protobuf:"varint,5,opt,name=control_favorite_movie,json=controlFavoriteMovie,proto3" json:"control_favorite_movie,omitempty"`
	ControlDashboard     bool     `protobuf:"varint,6,opt,name=control_dashboard,json=controlDashboard,proto3" json:"control_dashboard,omitempty"`
	ControlTariff        bool     `protobuf:"varint,7,opt,name=control_tariff,json=controlTariff,proto3" json:"control_tariff,omitempty"`
	ControlPermissions   bool     `protobuf:"varint,8,opt,name=control_permissions,json=controlPermissions,proto3" json:"control_permissions,omitempty"`
	ControlMovie         bool     `protobuf:"varint,9,opt,name=control_movie,json=controlMovie,proto3" json:"control_movie,omitempty"`
	ControlNotification  bool     `protobuf:"varint,10,opt,name=control_notification,json=controlNotification,proto3" json:"control_notification,omitempty"`
	ControlAdmin         bool     `protobuf:"varint,11,opt,name=control_admin,json=controlAdmin,proto3" json:"control_admin,omitempty"`
	ControlGenre         bool     `protobuf:"varint,12,opt,name=control_genre,json=controlGenre,proto3" json:"control_genre,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateList) Reset()         { *m = UpdateList{} }
func (m *UpdateList) String() string { return proto.CompactTextString(m) }
func (*UpdateList) ProtoMessage()    {}
func (*UpdateList) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{12}
}

func (m *UpdateList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateList.Unmarshal(m, b)
}
func (m *UpdateList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateList.Marshal(b, m, deterministic)
}
func (m *UpdateList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateList.Merge(m, src)
}
func (m *UpdateList) XXX_Size() int {
	return xxx_messageInfo_UpdateList.Size(m)
}
func (m *UpdateList) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateList.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateList proto.InternalMessageInfo

func (m *UpdateList) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateList) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *UpdateList) GetControlMovieCreators() bool {
	if m != nil {
		return m.ControlMovieCreators
	}
	return false
}

func (m *UpdateList) GetControlCategory() bool {
	if m != nil {
		return m.ControlCategory
	}
	return false
}

func (m *UpdateList) GetControlFavoriteMovie() bool {
	if m != nil {
		return m.ControlFavoriteMovie
	}
	return false
}

func (m *UpdateList) GetControlDashboard() bool {
	if m != nil {
		return m.ControlDashboard
	}
	return false
}

func (m *UpdateList) GetControlTariff() bool {
	if m != nil {
		return m.ControlTariff
	}
	return false
}

func (m *UpdateList) GetControlPermissions() bool {
	if m != nil {
		return m.ControlPermissions
	}
	return false
}

func (m *UpdateList) GetControlMovie() bool {
	if m != nil {
		return m.ControlMovie
	}
	return false
}

func (m *UpdateList) GetControlNotification() bool {
	if m != nil {
		return m.ControlNotification
	}
	return false
}

func (m *UpdateList) GetControlAdmin() bool {
	if m != nil {
		return m.ControlAdmin
	}
	return false
}

func (m *UpdateList) GetControlGenre() bool {
	if m != nil {
		return m.ControlGenre
	}
	return false
}

type UpdateResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	ControlMovieCreators bool     `protobuf:"varint,3,opt,name=control_movie_creators,json=controlMovieCreators,proto3" json:"control_movie_creators,omitempty"`
	ControlCategory      bool     `protobuf:"varint,4,opt,name=control_category,json=controlCategory,proto3" json:"control_category,omitempty"`
	ControlFavoriteMovie bool     `protobuf:"varint,5,opt,name=control_favorite_movie,json=controlFavoriteMovie,proto3" json:"control_favorite_movie,omitempty"`
	ControlDashboard     bool     `protobuf:"varint,6,opt,name=control_dashboard,json=controlDashboard,proto3" json:"control_dashboard,omitempty"`
	ControlTariff        bool     `protobuf:"varint,7,opt,name=control_tariff,json=controlTariff,proto3" json:"control_tariff,omitempty"`
	ControlPermissions   bool     `protobuf:"varint,8,opt,name=control_permissions,json=controlPermissions,proto3" json:"control_permissions,omitempty"`
	ControlMovie         bool     `protobuf:"varint,9,opt,name=control_movie,json=controlMovie,proto3" json:"control_movie,omitempty"`
	ControlNotification  bool     `protobuf:"varint,10,opt,name=control_notification,json=controlNotification,proto3" json:"control_notification,omitempty"`
	ControlAdmin         bool     `protobuf:"varint,11,opt,name=control_admin,json=controlAdmin,proto3" json:"control_admin,omitempty"`
	ControlGenre         bool     `protobuf:"varint,12,opt,name=control_genre,json=controlGenre,proto3" json:"control_genre,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateResponse) Reset()         { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()    {}
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{13}
}

func (m *UpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateResponse.Unmarshal(m, b)
}
func (m *UpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateResponse.Marshal(b, m, deterministic)
}
func (m *UpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateResponse.Merge(m, src)
}
func (m *UpdateResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateResponse.Size(m)
}
func (m *UpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateResponse proto.InternalMessageInfo

func (m *UpdateResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateResponse) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *UpdateResponse) GetControlMovieCreators() bool {
	if m != nil {
		return m.ControlMovieCreators
	}
	return false
}

func (m *UpdateResponse) GetControlCategory() bool {
	if m != nil {
		return m.ControlCategory
	}
	return false
}

func (m *UpdateResponse) GetControlFavoriteMovie() bool {
	if m != nil {
		return m.ControlFavoriteMovie
	}
	return false
}

func (m *UpdateResponse) GetControlDashboard() bool {
	if m != nil {
		return m.ControlDashboard
	}
	return false
}

func (m *UpdateResponse) GetControlTariff() bool {
	if m != nil {
		return m.ControlTariff
	}
	return false
}

func (m *UpdateResponse) GetControlPermissions() bool {
	if m != nil {
		return m.ControlPermissions
	}
	return false
}

func (m *UpdateResponse) GetControlMovie() bool {
	if m != nil {
		return m.ControlMovie
	}
	return false
}

func (m *UpdateResponse) GetControlNotification() bool {
	if m != nil {
		return m.ControlNotification
	}
	return false
}

func (m *UpdateResponse) GetControlAdmin() bool {
	if m != nil {
		return m.ControlAdmin
	}
	return false
}

func (m *UpdateResponse) GetControlGenre() bool {
	if m != nil {
		return m.ControlGenre
	}
	return false
}

// DeleteRoleId
type SuccessResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SuccessResponse) Reset()         { *m = SuccessResponse{} }
func (m *SuccessResponse) String() string { return proto.CompactTextString(m) }
func (*SuccessResponse) ProtoMessage()    {}
func (*SuccessResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{14}
}

func (m *SuccessResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SuccessResponse.Unmarshal(m, b)
}
func (m *SuccessResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SuccessResponse.Marshal(b, m, deterministic)
}
func (m *SuccessResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SuccessResponse.Merge(m, src)
}
func (m *SuccessResponse) XXX_Size() int {
	return xxx_messageInfo_SuccessResponse.Size(m)
}
func (m *SuccessResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SuccessResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SuccessResponse proto.InternalMessageInfo

func (m *SuccessResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*Admin)(nil), "genproto.Admin")
	proto.RegisterType((*Customer)(nil), "genproto.Customer")
	proto.RegisterType((*UserActivity)(nil), "genproto.UserActivity")
	proto.RegisterType((*UserActivity_User)(nil), "genproto.UserActivity.User")
	proto.RegisterType((*Permission)(nil), "genproto.Permission")
	proto.RegisterType((*DeleteRequest)(nil), "genproto.DeleteRequest")
	proto.RegisterType((*Empty)(nil), "genproto.Empty")
	proto.RegisterType((*ListRequest)(nil), "genproto.ListRequest")
	proto.RegisterType((*IdMessage)(nil), "genproto.IdMessage")
	proto.RegisterType((*Role)(nil), "genproto.Role")
	proto.RegisterType((*RoleListRequestId)(nil), "genproto.RoleListRequestId")
	proto.RegisterType((*GetRequest)(nil), "genproto.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "genproto.GetResponse")
	proto.RegisterType((*UpdateList)(nil), "genproto.UpdateList")
	proto.RegisterType((*UpdateResponse)(nil), "genproto.UpdateResponse")
	proto.RegisterType((*SuccessResponse)(nil), "genproto.SuccessResponse")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 935 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x57, 0xdd, 0x6e, 0x1c, 0x35,
	0x14, 0xd6, 0xfe, 0x25, 0xb3, 0x67, 0xb3, 0xf9, 0x71, 0x43, 0x18, 0x1a, 0xaa, 0xa6, 0x53, 0x21,
	0x05, 0x21, 0x25, 0xa2, 0x20, 0xee, 0x37, 0x29, 0x54, 0x2b, 0x51, 0x8a, 0x86, 0xb6, 0x17, 0x08,
	0x69, 0xe4, 0x8c, 0x3d, 0x1b, 0x2b, 0x33, 0xe3, 0xc1, 0xf6, 0x2e, 0xca, 0x2b, 0xf1, 0x0a, 0xbc,
	0x02, 0x4f, 0xc2, 0x15, 0x48, 0x3c, 0x00, 0xf2, 0xb1, 0xbd, 0x3b, 0x64, 0x95, 0x5e, 0xe5, 0x2e,
	0xb9, 0xf3, 0xf9, 0xbe, 0x63, 0x9f, 0xe3, 0x73, 0x3e, 0x9f, 0xd9, 0x05, 0x98, 0x6b, 0xae, 0x4e,
	0x1a, 0x25, 0x8d, 0x24, 0xd1, 0x8c, 0xd7, 0xb8, 0x4a, 0x7e, 0xef, 0xc2, 0x60, 0xc2, 0x2a, 0x51,
	0x93, 0x6d, 0xe8, 0x0a, 0x16, 0x77, 0x8e, 0x3a, 0xc7, 0xc3, 0xb4, 0x2b, 0x18, 0x79, 0x06, 0x5b,
	0x34, 0xcf, 0xb9, 0xd6, 0x99, 0x91, 0x57, 0xbc, 0x8e, 0xbb, 0xc8, 0x8c, 0x1c, 0xf6, 0xd6, 0x42,
	0x84, 0x40, 0xbf, 0xa6, 0x15, 0x8f, 0x7b, 0x48, 0xe1, 0x9a, 0x3c, 0x86, 0xc8, 0x06, 0x42, 0xbc,
	0x8f, 0xf8, 0xd2, 0xb6, 0x5c, 0x43, 0xb5, 0xfe, 0x4d, 0x2a, 0x16, 0x0f, 0x1c, 0x17, 0x6c, 0xb2,
	0x0f, 0x83, 0xe6, 0x52, 0xd6, 0x3c, 0xde, 0x40, 0xc2, 0x19, 0xe4, 0x00, 0x36, 0x68, 0x6e, 0xc4,
	0x82, 0xc7, 0x9b, 0x47, 0x9d, 0xe3, 0x28, 0xf5, 0x16, 0x79, 0x02, 0x90, 0x2b, 0x4e, 0x0d, 0x67,
	0x19, 0x35, 0xf1, 0x08, 0xb7, 0x0c, 0x3d, 0x32, 0x31, 0x96, 0x9e, 0x37, 0x2c, 0xd0, 0x5b, 0x8e,
	0xf6, 0xc8, 0xc4, 0x90, 0x6f, 0x60, 0xd4, 0x70, 0x55, 0x09, 0xad, 0x85, 0xac, 0x75, 0x3c, 0x3e,
	0xea, 0x1d, 0x8f, 0x5e, 0xec, 0x9f, 0x84, 0xa2, 0x9c, 0xfc, 0xb8, 0x24, 0xd3, 0xb6, 0x63, 0xf2,
	0x47, 0x1f, 0xa2, 0xf3, 0xb9, 0x36, 0xb2, 0xe2, 0xea, 0x0e, 0xeb, 0x55, 0x52, 0x6d, 0xda, 0xf5,
	0x0a, 0xf6, 0x1d, 0xd6, 0xeb, 0x33, 0xd8, 0x46, 0x87, 0x6c, 0xc1, 0x95, 0x28, 0x04, 0x67, 0x71,
	0x84, 0xfc, 0x18, 0xd1, 0xf7, 0x1e, 0x24, 0x31, 0x6c, 0x52, 0xc6, 0x14, 0xd7, 0x3a, 0x1e, 0xe2,
	0xb1, 0xc1, 0xb4, 0x07, 0xcf, 0x78, 0xcd, 0xb8, 0x8a, 0x01, 0x09, 0x6f, 0x91, 0x04, 0xc6, 0xb6,
	0xaa, 0x99, 0x2c, 0xb2, 0x0b, 0xa1, 0xcc, 0xa5, 0xef, 0xc5, 0xc8, 0x82, 0x6f, 0x8a, 0x33, 0x0b,
	0x61, 0x52, 0x0b, 0x6a, 0xa8, 0xf2, 0x9d, 0xf0, 0x16, 0x39, 0x84, 0xe1, 0x4c, 0xca, 0x59, 0xc9,
	0x33, 0xc1, 0xe2, 0xb1, 0xbb, 0x9f, 0x03, 0xa6, 0x8c, 0x3c, 0x85, 0x51, 0x41, 0x73, 0x7e, 0x21,
	0xe5, 0x95, 0xa5, 0xb7, 0x91, 0x86, 0x00, 0x4d, 0x19, 0xf9, 0x04, 0x22, 0xda, 0x34, 0x6e, 0xf3,
	0x8e, 0x4f, 0xd6, 0xda, 0x53, 0x76, 0x43, 0x1d, 0xbb, 0x1f, 0x56, 0xc7, 0xde, 0x4d, 0x75, 0x3c,
	0x01, 0x60, 0xbc, 0xe4, 0x9e, 0x26, 0x8e, 0xf6, 0xc8, 0xc4, 0xd8, 0xac, 0x8b, 0xbc, 0xf2, 0x4d,
	0x7e, 0xe4, 0xb2, 0x2e, 0xf2, 0xca, 0x75, 0xd8, 0x76, 0xac, 0xa4, 0xa6, 0x90, 0xaa, 0x8a, 0xf7,
	0x8f, 0x3a, 0xc7, 0x83, 0x74, 0x69, 0x27, 0x7f, 0x76, 0x61, 0xeb, 0x9d, 0xe6, 0x6a, 0x62, 0x5b,
	0x22, 0xcc, 0xf5, 0x9a, 0x82, 0x4e, 0xa1, 0x6f, 0x9f, 0x0a, 0x2a, 0x67, 0xf4, 0xe2, 0x70, 0xa5,
	0xc7, 0xf6, 0x2e, 0x34, 0x52, 0x74, 0xb4, 0xed, 0xe2, 0x25, 0xaf, 0x78, 0x6d, 0xbc, 0xa4, 0x82,
	0x69, 0xef, 0xe0, 0x97, 0xb6, 0x3c, 0x4e, 0x57, 0x43, 0x8f, 0x4c, 0x59, 0x90, 0x89, 0xac, 0xbd,
	0xac, 0xbc, 0x65, 0xb7, 0x15, 0x4a, 0x56, 0xd9, 0x82, 0x96, 0xf3, 0xa0, 0xac, 0xa1, 0x45, 0xde,
	0x5b, 0xc0, 0x96, 0xdc, 0x48, 0x4f, 0x6e, 0xba, 0x80, 0x46, 0x3a, 0x8a, 0x40, 0xdf, 0x88, 0x8a,
	0xa3, 0xac, 0x86, 0x29, 0xae, 0x1f, 0xff, 0x02, 0x7d, 0x9b, 0xec, 0xda, 0x3d, 0xc3, 0x33, 0xe8,
	0xde, 0x32, 0x36, 0x7a, 0x37, 0xc6, 0xc6, 0x52, 0xea, 0xfd, 0x96, 0xd4, 0x93, 0x33, 0x80, 0xd5,
	0x3b, 0x5d, 0x9e, 0xd9, 0x69, 0x9d, 0xb9, 0x0b, 0xbd, 0x2b, 0x7e, 0xed, 0xc3, 0xd8, 0xa5, 0xcf,
	0xa4, 0x17, 0x32, 0x49, 0x9e, 0xc2, 0xf8, 0x25, 0x36, 0x36, 0xe5, 0xbf, 0xce, 0xb9, 0x36, 0x37,
	0x53, 0x4d, 0x36, 0x61, 0xf0, 0x6d, 0xd5, 0x98, 0xeb, 0xe4, 0x0d, 0x8c, 0xbe, 0x17, 0xda, 0x04,
	0xbf, 0x03, 0xd8, 0xd0, 0x9c, 0xaa, 0xfc, 0xd2, 0xfb, 0x7a, 0xcb, 0xa6, 0x5a, 0x8a, 0x4a, 0x18,
	0x0c, 0x3a, 0x48, 0x9d, 0x61, 0x93, 0x6b, 0xe8, 0xcc, 0x5d, 0x6c, 0x90, 0xe2, 0x3a, 0x39, 0x84,
	0xe1, 0x94, 0xbd, 0xe6, 0x5a, 0xd3, 0x19, 0x5f, 0x0b, 0xfb, 0x57, 0x0f, 0xfa, 0xa9, 0x2c, 0xd7,
	0x08, 0x7b, 0xbe, 0x11, 0xa6, 0x0c, 0xb5, 0x73, 0x06, 0xf9, 0x1a, 0x0e, 0x72, 0x59, 0x1b, 0x25,
	0xcb, 0xac, 0x92, 0x0b, 0xc1, 0x33, 0xd4, 0xba, 0x54, 0x1a, 0x23, 0x46, 0xe9, 0xbe, 0x67, 0x5f,
	0x5b, 0xf2, 0xdc, 0x73, 0xe4, 0x73, 0xd8, 0x0d, 0xbb, 0x72, 0x6a, 0xf8, 0x4c, 0xaa, 0x6b, 0xac,
	0x70, 0x94, 0xee, 0x78, 0xfc, 0xdc, 0xc3, 0xed, 0x00, 0x05, 0x5d, 0x48, 0x25, 0x0c, 0x77, 0x91,
	0x50, 0x3f, 0xab, 0x00, 0xdf, 0x79, 0x12, 0x03, 0x91, 0x2f, 0x60, 0x2f, 0xec, 0x62, 0x54, 0x5f,
	0x5e, 0x48, 0xaa, 0x18, 0x8a, 0x2a, 0x4a, 0x43, 0xe4, 0x97, 0x01, 0xb7, 0x13, 0x2a, 0x38, 0x1b,
	0xaa, 0x44, 0x51, 0xf8, 0x09, 0x36, 0xf6, 0xe8, 0x5b, 0x04, 0xc9, 0x29, 0x3c, 0x0a, 0x6e, 0xed,
	0x11, 0xee, 0xa6, 0x19, 0xf1, 0xd4, 0x4a, 0x17, 0x9a, 0x3c, 0x87, 0xf1, 0xff, 0x6a, 0x83, 0x83,
	0x2d, 0x4a, 0xb7, 0xda, 0x25, 0x21, 0x5f, 0x42, 0xb8, 0x41, 0x56, 0x4b, 0x23, 0x0a, 0x91, 0x53,
	0x7c, 0x1d, 0x80, 0xbe, 0x21, 0xe2, 0x0f, 0x2d, 0xaa, 0x7d, 0x2e, 0xb5, 0xdf, 0x4f, 0x1c, 0x7c,
	0xab, 0x73, 0xdd, 0x37, 0xb5, 0xe5, 0x34, 0xe3, 0xb5, 0xe2, 0x38, 0x00, 0x57, 0x4e, 0xaf, 0x2c,
	0x96, 0x3c, 0x87, 0x3d, 0xdb, 0xeb, 0x96, 0xbc, 0xa6, 0x6c, 0x4d, 0x11, 0x9f, 0x02, 0xbc, 0xe2,
	0xe6, 0x36, 0x99, 0xfe, 0xd3, 0x83, 0x11, 0xd2, 0xba, 0x91, 0xb5, 0x7e, 0x90, 0xcd, 0x7d, 0x90,
	0xcd, 0xdf, 0x3d, 0x80, 0x77, 0xf8, 0xd1, 0xb2, 0xca, 0x79, 0x68, 0xf9, 0x3d, 0x68, 0xf9, 0xbf,
	0x3d, 0xd8, 0x76, 0x2d, 0x7f, 0x78, 0xe9, 0xf7, 0xa8, 0xed, 0xcf, 0x60, 0xe7, 0xa7, 0x39, 0xfe,
	0x8d, 0xb8, 0xad, 0xed, 0x67, 0x1f, 0xff, 0xfc, 0x51, 0xf8, 0xb5, 0x78, 0x6a, 0x7f, 0x37, 0x65,
	0x9a, 0xab, 0x85, 0xc8, 0xf9, 0xc5, 0x06, 0x62, 0x5f, 0xfd, 0x17, 0x00, 0x00, 0xff, 0xff, 0xd6,
	0x93, 0x82, 0xdc, 0xfe, 0x0d, 0x00, 0x00,
}
