// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: global_variables_service.proto

package inquiry_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAllVariableRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Offset int64 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit  int64 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *GetAllVariableRequest) Reset() {
	*x = GetAllVariableRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_global_variables_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllVariableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllVariableRequest) ProtoMessage() {}

func (x *GetAllVariableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_global_variables_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllVariableRequest.ProtoReflect.Descriptor instead.
func (*GetAllVariableRequest) Descriptor() ([]byte, []int) {
	return file_global_variables_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetAllVariableRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetAllVariableRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

var File_global_variables_service_proto protoreflect.FileDescriptor

var file_global_variables_service_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x5f, 0x76, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c,
	0x65, 0x73, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x16, 0x67, 0x6c, 0x6f, 0x62,
	0x61, 0x6c, 0x5f, 0x76, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x45, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73,
	0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x32, 0xf4, 0x01, 0x0a, 0x16, 0x47, 0x6c, 0x6f, 0x62, 0x61,
	0x6c, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x4a, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x26, 0x2e, 0x67, 0x65,
	0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x47, 0x6c, 0x6f,
	0x62, 0x61, 0x6c, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x4e, 0x0a,
	0x06, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x12, 0x1f, 0x2e, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x67, 0x65, 0x6e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62,
	0x6c, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3e, 0x0a,
	0x03, 0x47, 0x65, 0x74, 0x12, 0x1b, 0x2e, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x4b, 0x65,
	0x79, 0x1a, 0x18, 0x2e, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x6c, 0x6f,
	0x62, 0x61, 0x6c, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x22, 0x00, 0x42, 0x1a, 0x5a,
	0x18, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x69, 0x6e, 0x71, 0x75, 0x69, 0x72,
	0x79, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_global_variables_service_proto_rawDescOnce sync.Once
	file_global_variables_service_proto_rawDescData = file_global_variables_service_proto_rawDesc
)

func file_global_variables_service_proto_rawDescGZIP() []byte {
	file_global_variables_service_proto_rawDescOnce.Do(func() {
		file_global_variables_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_global_variables_service_proto_rawDescData)
	})
	return file_global_variables_service_proto_rawDescData
}

var file_global_variables_service_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_global_variables_service_proto_goTypes = []interface{}{
	(*GetAllVariableRequest)(nil),        // 0: genproto.GetAllVariableRequest
	(*UpdateGlobalVariablesRequest)(nil), // 1: genproto.UpdateGlobalVariablesRequest
	(*GlobalVariableKey)(nil),            // 2: genproto.GlobalVariableKey
	(*emptypb.Empty)(nil),                // 3: google.protobuf.Empty
	(*GetAllVariablesResponse)(nil),      // 4: genproto.GetAllVariablesResponse
	(*GlobalVariable)(nil),               // 5: genproto.GlobalVariable
}
var file_global_variables_service_proto_depIdxs = []int32{
	1, // 0: genproto.GlobalVariablesService.Update:input_type -> genproto.UpdateGlobalVariablesRequest
	0, // 1: genproto.GlobalVariablesService.GetAll:input_type -> genproto.GetAllVariableRequest
	2, // 2: genproto.GlobalVariablesService.Get:input_type -> genproto.GlobalVariableKey
	3, // 3: genproto.GlobalVariablesService.Update:output_type -> google.protobuf.Empty
	4, // 4: genproto.GlobalVariablesService.GetAll:output_type -> genproto.GetAllVariablesResponse
	5, // 5: genproto.GlobalVariablesService.Get:output_type -> genproto.GlobalVariable
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_global_variables_service_proto_init() }
func file_global_variables_service_proto_init() {
	if File_global_variables_service_proto != nil {
		return
	}
	file_global_variables_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_global_variables_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllVariableRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_global_variables_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_global_variables_service_proto_goTypes,
		DependencyIndexes: file_global_variables_service_proto_depIdxs,
		MessageInfos:      file_global_variables_service_proto_msgTypes,
	}.Build()
	File_global_variables_service_proto = out.File
	file_global_variables_service_proto_rawDesc = nil
	file_global_variables_service_proto_goTypes = nil
	file_global_variables_service_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GlobalVariablesServiceClient is the client API for GlobalVariablesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GlobalVariablesServiceClient interface {
	Update(ctx context.Context, in *UpdateGlobalVariablesRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetAll(ctx context.Context, in *GetAllVariableRequest, opts ...grpc.CallOption) (*GetAllVariablesResponse, error)
	Get(ctx context.Context, in *GlobalVariableKey, opts ...grpc.CallOption) (*GlobalVariable, error)
}

type globalVariablesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGlobalVariablesServiceClient(cc grpc.ClientConnInterface) GlobalVariablesServiceClient {
	return &globalVariablesServiceClient{cc}
}

func (c *globalVariablesServiceClient) Update(ctx context.Context, in *UpdateGlobalVariablesRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/genproto.GlobalVariablesService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *globalVariablesServiceClient) GetAll(ctx context.Context, in *GetAllVariableRequest, opts ...grpc.CallOption) (*GetAllVariablesResponse, error) {
	out := new(GetAllVariablesResponse)
	err := c.cc.Invoke(ctx, "/genproto.GlobalVariablesService/GetAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *globalVariablesServiceClient) Get(ctx context.Context, in *GlobalVariableKey, opts ...grpc.CallOption) (*GlobalVariable, error) {
	out := new(GlobalVariable)
	err := c.cc.Invoke(ctx, "/genproto.GlobalVariablesService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GlobalVariablesServiceServer is the server API for GlobalVariablesService service.
type GlobalVariablesServiceServer interface {
	Update(context.Context, *UpdateGlobalVariablesRequest) (*emptypb.Empty, error)
	GetAll(context.Context, *GetAllVariableRequest) (*GetAllVariablesResponse, error)
	Get(context.Context, *GlobalVariableKey) (*GlobalVariable, error)
}

// UnimplementedGlobalVariablesServiceServer can be embedded to have forward compatible implementations.
type UnimplementedGlobalVariablesServiceServer struct {
}

func (*UnimplementedGlobalVariablesServiceServer) Update(context.Context, *UpdateGlobalVariablesRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedGlobalVariablesServiceServer) GetAll(context.Context, *GetAllVariableRequest) (*GetAllVariablesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAll not implemented")
}
func (*UnimplementedGlobalVariablesServiceServer) Get(context.Context, *GlobalVariableKey) (*GlobalVariable, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}

func RegisterGlobalVariablesServiceServer(s *grpc.Server, srv GlobalVariablesServiceServer) {
	s.RegisterService(&_GlobalVariablesService_serviceDesc, srv)
}

func _GlobalVariablesService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateGlobalVariablesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GlobalVariablesServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/genproto.GlobalVariablesService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GlobalVariablesServiceServer).Update(ctx, req.(*UpdateGlobalVariablesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GlobalVariablesService_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllVariableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GlobalVariablesServiceServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/genproto.GlobalVariablesService/GetAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GlobalVariablesServiceServer).GetAll(ctx, req.(*GetAllVariableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GlobalVariablesService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GlobalVariableKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GlobalVariablesServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/genproto.GlobalVariablesService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GlobalVariablesServiceServer).Get(ctx, req.(*GlobalVariableKey))
	}
	return interceptor(ctx, in, info, handler)
}

var _GlobalVariablesService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "genproto.GlobalVariablesService",
	HandlerType: (*GlobalVariablesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Update",
			Handler:    _GlobalVariablesService_Update_Handler,
		},
		{
			MethodName: "GetAll",
			Handler:    _GlobalVariablesService_GetAll_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _GlobalVariablesService_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "global_variables_service.proto",
}
