// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: global_variables.proto

package inquiry_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GlobalVariable struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *GlobalVariable) Reset() {
	*x = GlobalVariable{}
	if protoimpl.UnsafeEnabled {
		mi := &file_global_variables_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GlobalVariable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalVariable) ProtoMessage() {}

func (x *GlobalVariable) ProtoReflect() protoreflect.Message {
	mi := &file_global_variables_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalVariable.ProtoReflect.Descriptor instead.
func (*GlobalVariable) Descriptor() ([]byte, []int) {
	return file_global_variables_proto_rawDescGZIP(), []int{0}
}

func (x *GlobalVariable) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GlobalVariable) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type GlobalVariableKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *GlobalVariableKey) Reset() {
	*x = GlobalVariableKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_global_variables_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GlobalVariableKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalVariableKey) ProtoMessage() {}

func (x *GlobalVariableKey) ProtoReflect() protoreflect.Message {
	mi := &file_global_variables_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalVariableKey.ProtoReflect.Descriptor instead.
func (*GlobalVariableKey) Descriptor() ([]byte, []int) {
	return file_global_variables_proto_rawDescGZIP(), []int{1}
}

func (x *GlobalVariableKey) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetAllVariablesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GlobalVariables []*GlobalVariable `protobuf:"bytes,1,rep,name=global_variables,json=globalVariables,proto3" json:"global_variables,omitempty"`
	Count           int32             `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *GetAllVariablesResponse) Reset() {
	*x = GetAllVariablesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_global_variables_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllVariablesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllVariablesResponse) ProtoMessage() {}

func (x *GetAllVariablesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_global_variables_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllVariablesResponse.ProtoReflect.Descriptor instead.
func (*GetAllVariablesResponse) Descriptor() ([]byte, []int) {
	return file_global_variables_proto_rawDescGZIP(), []int{2}
}

func (x *GetAllVariablesResponse) GetGlobalVariables() []*GlobalVariable {
	if x != nil {
		return x.GlobalVariables
	}
	return nil
}

func (x *GetAllVariablesResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type UpdateGlobalVariablesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GlobalVariables []*GlobalVariable `protobuf:"bytes,1,rep,name=global_variables,json=globalVariables,proto3" json:"global_variables,omitempty"`
}

func (x *UpdateGlobalVariablesRequest) Reset() {
	*x = UpdateGlobalVariablesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_global_variables_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateGlobalVariablesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGlobalVariablesRequest) ProtoMessage() {}

func (x *UpdateGlobalVariablesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_global_variables_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGlobalVariablesRequest.ProtoReflect.Descriptor instead.
func (*UpdateGlobalVariablesRequest) Descriptor() ([]byte, []int) {
	return file_global_variables_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateGlobalVariablesRequest) GetGlobalVariables() []*GlobalVariable {
	if x != nil {
		return x.GlobalVariables
	}
	return nil
}

var File_global_variables_proto protoreflect.FileDescriptor

var file_global_variables_proto_rawDesc = []byte{
	0x0a, 0x16, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x5f, 0x76, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c,
	0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x38, 0x0a, 0x0e, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x56, 0x61, 0x72, 0x69,
	0x61, 0x62, 0x6c, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x25, 0x0a, 0x11,
	0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x4b, 0x65,
	0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x22, 0x74, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x56, 0x61, 0x72,
	0x69, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x43,
	0x0a, 0x10, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x5f, 0x76, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x67, 0x65, 0x6e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62,
	0x6c, 0x65, 0x52, 0x0f, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62,
	0x6c, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x63, 0x0a, 0x1c, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c,
	0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x43, 0x0a, 0x10, 0x67, 0x6c, 0x6f,
	0x62, 0x61, 0x6c, 0x5f, 0x76, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47,
	0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x0f, 0x67,
	0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x42, 0x1a,
	0x5a, 0x18, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x69, 0x6e, 0x71, 0x75, 0x69,
	0x72, 0x79, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_global_variables_proto_rawDescOnce sync.Once
	file_global_variables_proto_rawDescData = file_global_variables_proto_rawDesc
)

func file_global_variables_proto_rawDescGZIP() []byte {
	file_global_variables_proto_rawDescOnce.Do(func() {
		file_global_variables_proto_rawDescData = protoimpl.X.CompressGZIP(file_global_variables_proto_rawDescData)
	})
	return file_global_variables_proto_rawDescData
}

var file_global_variables_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_global_variables_proto_goTypes = []interface{}{
	(*GlobalVariable)(nil),               // 0: genproto.GlobalVariable
	(*GlobalVariableKey)(nil),            // 1: genproto.GlobalVariableKey
	(*GetAllVariablesResponse)(nil),      // 2: genproto.GetAllVariablesResponse
	(*UpdateGlobalVariablesRequest)(nil), // 3: genproto.UpdateGlobalVariablesRequest
}
var file_global_variables_proto_depIdxs = []int32{
	0, // 0: genproto.GetAllVariablesResponse.global_variables:type_name -> genproto.GlobalVariable
	0, // 1: genproto.UpdateGlobalVariablesRequest.global_variables:type_name -> genproto.GlobalVariable
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_global_variables_proto_init() }
func file_global_variables_proto_init() {
	if File_global_variables_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_global_variables_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GlobalVariable); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_global_variables_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GlobalVariableKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_global_variables_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllVariablesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_global_variables_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateGlobalVariablesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_global_variables_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_global_variables_proto_goTypes,
		DependencyIndexes: file_global_variables_proto_depIdxs,
		MessageInfos:      file_global_variables_proto_msgTypes,
	}.Build()
	File_global_variables_proto = out.File
	file_global_variables_proto_rawDesc = nil
	file_global_variables_proto_goTypes = nil
	file_global_variables_proto_depIdxs = nil
}
