// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: inquiry_service.proto

package inquiry_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAllInquiryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Offset       int64  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit        int64  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Name         string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	StatusId     string `protobuf:"bytes,4,opt,name=status_id,json=statusId,proto3" json:"status_id,omitempty"`
	ResearcherId string `protobuf:"bytes,5,opt,name=researcher_id,json=researcherId,proto3" json:"researcher_id,omitempty"`
	CompanyId    string `protobuf:"bytes,6,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
}

func (x *GetAllInquiryRequest) Reset() {
	*x = GetAllInquiryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inquiry_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllInquiryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllInquiryRequest) ProtoMessage() {}

func (x *GetAllInquiryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inquiry_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllInquiryRequest.ProtoReflect.Descriptor instead.
func (*GetAllInquiryRequest) Descriptor() ([]byte, []int) {
	return file_inquiry_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetAllInquiryRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetAllInquiryRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetAllInquiryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetAllInquiryRequest) GetStatusId() string {
	if x != nil {
		return x.StatusId
	}
	return ""
}

func (x *GetAllInquiryRequest) GetResearcherId() string {
	if x != nil {
		return x.ResearcherId
	}
	return ""
}

func (x *GetAllInquiryRequest) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

var File_inquiry_service_proto protoreflect.FileDescriptor

var file_inquiry_service_proto_rawDesc = []byte{
	0x0a, 0x15, 0x69, 0x6e, 0x71, 0x75, 0x69, 0x72, 0x79, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x0d, 0x69, 0x6e, 0x71, 0x75, 0x69, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb9, 0x01,
	0x0a, 0x14, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x49, 0x6e, 0x71, 0x75, 0x69, 0x72, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c,
	0x69, 0x6d, 0x69, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x73, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65,
	0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6f,
	0x6d, 0x70, 0x61, 0x6e, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x49, 0x64, 0x32, 0x86, 0x07, 0x0a, 0x0e, 0x49, 0x6e,
	0x71, 0x75, 0x69, 0x72, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x32, 0x0a, 0x06,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x11, 0x2e, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x49, 0x6e, 0x71, 0x75, 0x69, 0x72, 0x79, 0x1a, 0x13, 0x2e, 0x67, 0x65, 0x6e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49, 0x6e, 0x71, 0x75, 0x69, 0x72, 0x79, 0x49, 0x64, 0x22, 0x00,
	0x12, 0x32, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x11, 0x2e, 0x67, 0x65, 0x6e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49, 0x6e, 0x71, 0x75, 0x69, 0x72, 0x79, 0x1a, 0x13, 0x2e,
	0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49, 0x6e, 0x71, 0x75, 0x69, 0x72, 0x79,
	0x49, 0x64, 0x22, 0x00, 0x12, 0x2f, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x13, 0x2e, 0x67, 0x65,
	0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49, 0x6e, 0x71, 0x75, 0x69, 0x72, 0x79, 0x49, 0x64,
	0x1a, 0x11, 0x2e, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49, 0x6e, 0x71, 0x75,
	0x69, 0x72, 0x79, 0x22, 0x00, 0x12, 0x4b, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x12,
	0x1e, 0x2e, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c,
	0x6c, 0x49, 0x6e, 0x71, 0x75, 0x69, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1f, 0x2e, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c,
	0x6c, 0x49, 0x6e, 0x71, 0x75, 0x69, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x37, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x13, 0x2e, 0x67,
	0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49, 0x6e, 0x71, 0x75, 0x69, 0x72, 0x79, 0x49,
	0x64, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x3f, 0x0a, 0x0c, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x15, 0x2e, 0x67, 0x65,
	0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x4e, 0x6f, 0x74,
	0x65, 0x73, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x56, 0x0a, 0x13,
	0x41, 0x64, 0x64, 0x49, 0x6e, 0x71, 0x75, 0x69, 0x72, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x54, 0x61,
	0x62, 0x6c, 0x65, 0x12, 0x1f, 0x2e, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49,
	0x6e, 0x71, 0x75, 0x69, 0x72, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x4d,
	0x6f, 0x64, 0x65, 0x6c, 0x1a, 0x1c, 0x2e, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x49, 0x6e, 0x71, 0x75, 0x69, 0x72, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x54, 0x61, 0x62, 0x6c, 0x65,
	0x49, 0x64, 0x22, 0x00, 0x12, 0x56, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x71, 0x75, 0x69,
	0x72, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x1c, 0x2e, 0x67, 0x65,
	0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49, 0x6e, 0x71, 0x75, 0x69, 0x72, 0x79, 0x54, 0x69,
	0x6d, 0x65, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x64, 0x1a, 0x1f, 0x2e, 0x67, 0x65, 0x6e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49, 0x6e, 0x71, 0x75, 0x69, 0x72, 0x79, 0x54, 0x69, 0x6d, 0x65,
	0x54, 0x61, 0x62, 0x6c, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x22, 0x00, 0x12, 0x50, 0x0a, 0x16,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x71, 0x75, 0x69, 0x72, 0x79, 0x54, 0x69, 0x6d,
	0x65, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x1c, 0x2e, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x49, 0x6e, 0x71, 0x75, 0x69, 0x72, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x54, 0x61, 0x62,
	0x6c, 0x65, 0x49, 0x64, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x67,
	0x0a, 0x14, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x71, 0x75, 0x69, 0x72, 0x79, 0x54, 0x69, 0x6d, 0x65,
	0x54, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x12, 0x25, 0x2e, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x71, 0x75, 0x69, 0x72, 0x79, 0x54, 0x69, 0x6d, 0x65,
	0x54, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e,
	0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x71, 0x75,
	0x69, 0x72, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4c, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x43, 0x61,
	0x6c, 0x65, 0x6e, 0x64, 0x61, 0x72, 0x12, 0x1c, 0x2e, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x61, 0x6c, 0x65, 0x6e, 0x64, 0x61, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x47, 0x65, 0x74, 0x43, 0x61, 0x6c, 0x65, 0x6e, 0x64, 0x61, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5b, 0x0a, 0x16, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x49,
	0x6e, 0x71, 0x75, 0x69, 0x72, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x12,
	0x27, 0x2e, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x49, 0x6e, 0x71, 0x75, 0x69, 0x72, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x54, 0x61, 0x62, 0x6c,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x22, 0x00, 0x42, 0x1a, 0x5a, 0x18, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x69,
	0x6e, 0x71, 0x75, 0x69, 0x72, 0x79, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_inquiry_service_proto_rawDescOnce sync.Once
	file_inquiry_service_proto_rawDescData = file_inquiry_service_proto_rawDesc
)

func file_inquiry_service_proto_rawDescGZIP() []byte {
	file_inquiry_service_proto_rawDescOnce.Do(func() {
		file_inquiry_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_inquiry_service_proto_rawDescData)
	})
	return file_inquiry_service_proto_rawDescData
}

var file_inquiry_service_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_inquiry_service_proto_goTypes = []interface{}{
	(*GetAllInquiryRequest)(nil),          // 0: genproto.GetAllInquiryRequest
	(*Inquiry)(nil),                       // 1: genproto.Inquiry
	(*InquiryId)(nil),                     // 2: genproto.InquiryId
	(*StatusNotes)(nil),                   // 3: genproto.StatusNotes
	(*InquiryTimeTableModel)(nil),         // 4: genproto.InquiryTimeTableModel
	(*InquiryTimeTableId)(nil),            // 5: genproto.InquiryTimeTableId
	(*GetInquiryTimeTablesRequest)(nil),   // 6: genproto.GetInquiryTimeTablesRequest
	(*GetCalendarRequest)(nil),            // 7: genproto.GetCalendarRequest
	(*DeleteInquiryTimeTableRequest)(nil), // 8: genproto.DeleteInquiryTimeTableRequest
	(*GetAllInquiryResponse)(nil),         // 9: genproto.GetAllInquiryResponse
	(*emptypb.Empty)(nil),                 // 10: google.protobuf.Empty
	(*GetInquiryTimeTablesResponse)(nil),  // 11: genproto.GetInquiryTimeTablesResponse
	(*GetCalendarResponse)(nil),           // 12: genproto.GetCalendarResponse
}
var file_inquiry_service_proto_depIdxs = []int32{
	1,  // 0: genproto.InquiryService.Create:input_type -> genproto.Inquiry
	1,  // 1: genproto.InquiryService.Update:input_type -> genproto.Inquiry
	2,  // 2: genproto.InquiryService.Get:input_type -> genproto.InquiryId
	0,  // 3: genproto.InquiryService.GetAll:input_type -> genproto.GetAllInquiryRequest
	2,  // 4: genproto.InquiryService.Delete:input_type -> genproto.InquiryId
	3,  // 5: genproto.InquiryService.UpdateStatus:input_type -> genproto.StatusNotes
	4,  // 6: genproto.InquiryService.AddInquiryTimeTable:input_type -> genproto.InquiryTimeTableModel
	5,  // 7: genproto.InquiryService.GetInquiryTimeTable:input_type -> genproto.InquiryTimeTableId
	5,  // 8: genproto.InquiryService.UpdateInquiryTimeTable:input_type -> genproto.InquiryTimeTableId
	6,  // 9: genproto.InquiryService.GetInquiryTimeTables:input_type -> genproto.GetInquiryTimeTablesRequest
	7,  // 10: genproto.InquiryService.GetCalendar:input_type -> genproto.GetCalendarRequest
	8,  // 11: genproto.InquiryService.DeleteInquiryTimeTable:input_type -> genproto.DeleteInquiryTimeTableRequest
	2,  // 12: genproto.InquiryService.Create:output_type -> genproto.InquiryId
	2,  // 13: genproto.InquiryService.Update:output_type -> genproto.InquiryId
	1,  // 14: genproto.InquiryService.Get:output_type -> genproto.Inquiry
	9,  // 15: genproto.InquiryService.GetAll:output_type -> genproto.GetAllInquiryResponse
	10, // 16: genproto.InquiryService.Delete:output_type -> google.protobuf.Empty
	10, // 17: genproto.InquiryService.UpdateStatus:output_type -> google.protobuf.Empty
	5,  // 18: genproto.InquiryService.AddInquiryTimeTable:output_type -> genproto.InquiryTimeTableId
	4,  // 19: genproto.InquiryService.GetInquiryTimeTable:output_type -> genproto.InquiryTimeTableModel
	10, // 20: genproto.InquiryService.UpdateInquiryTimeTable:output_type -> google.protobuf.Empty
	11, // 21: genproto.InquiryService.GetInquiryTimeTables:output_type -> genproto.GetInquiryTimeTablesResponse
	12, // 22: genproto.InquiryService.GetCalendar:output_type -> genproto.GetCalendarResponse
	10, // 23: genproto.InquiryService.DeleteInquiryTimeTable:output_type -> google.protobuf.Empty
	12, // [12:24] is the sub-list for method output_type
	0,  // [0:12] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_inquiry_service_proto_init() }
func file_inquiry_service_proto_init() {
	if File_inquiry_service_proto != nil {
		return
	}
	file_inquiry_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_inquiry_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllInquiryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_inquiry_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inquiry_service_proto_goTypes,
		DependencyIndexes: file_inquiry_service_proto_depIdxs,
		MessageInfos:      file_inquiry_service_proto_msgTypes,
	}.Build()
	File_inquiry_service_proto = out.File
	file_inquiry_service_proto_rawDesc = nil
	file_inquiry_service_proto_goTypes = nil
	file_inquiry_service_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// InquiryServiceClient is the client API for InquiryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type InquiryServiceClient interface {
	Create(ctx context.Context, in *Inquiry, opts ...grpc.CallOption) (*InquiryId, error)
	Update(ctx context.Context, in *Inquiry, opts ...grpc.CallOption) (*InquiryId, error)
	Get(ctx context.Context, in *InquiryId, opts ...grpc.CallOption) (*Inquiry, error)
	GetAll(ctx context.Context, in *GetAllInquiryRequest, opts ...grpc.CallOption) (*GetAllInquiryResponse, error)
	Delete(ctx context.Context, in *InquiryId, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UpdateStatus(ctx context.Context, in *StatusNotes, opts ...grpc.CallOption) (*emptypb.Empty, error)
	AddInquiryTimeTable(ctx context.Context, in *InquiryTimeTableModel, opts ...grpc.CallOption) (*InquiryTimeTableId, error)
	GetInquiryTimeTable(ctx context.Context, in *InquiryTimeTableId, opts ...grpc.CallOption) (*InquiryTimeTableModel, error)
	UpdateInquiryTimeTable(ctx context.Context, in *InquiryTimeTableId, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetInquiryTimeTables(ctx context.Context, in *GetInquiryTimeTablesRequest, opts ...grpc.CallOption) (*GetInquiryTimeTablesResponse, error)
	GetCalendar(ctx context.Context, in *GetCalendarRequest, opts ...grpc.CallOption) (*GetCalendarResponse, error)
	DeleteInquiryTimeTable(ctx context.Context, in *DeleteInquiryTimeTableRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type inquiryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInquiryServiceClient(cc grpc.ClientConnInterface) InquiryServiceClient {
	return &inquiryServiceClient{cc}
}

func (c *inquiryServiceClient) Create(ctx context.Context, in *Inquiry, opts ...grpc.CallOption) (*InquiryId, error) {
	out := new(InquiryId)
	err := c.cc.Invoke(ctx, "/genproto.InquiryService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inquiryServiceClient) Update(ctx context.Context, in *Inquiry, opts ...grpc.CallOption) (*InquiryId, error) {
	out := new(InquiryId)
	err := c.cc.Invoke(ctx, "/genproto.InquiryService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inquiryServiceClient) Get(ctx context.Context, in *InquiryId, opts ...grpc.CallOption) (*Inquiry, error) {
	out := new(Inquiry)
	err := c.cc.Invoke(ctx, "/genproto.InquiryService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inquiryServiceClient) GetAll(ctx context.Context, in *GetAllInquiryRequest, opts ...grpc.CallOption) (*GetAllInquiryResponse, error) {
	out := new(GetAllInquiryResponse)
	err := c.cc.Invoke(ctx, "/genproto.InquiryService/GetAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inquiryServiceClient) Delete(ctx context.Context, in *InquiryId, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/genproto.InquiryService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inquiryServiceClient) UpdateStatus(ctx context.Context, in *StatusNotes, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/genproto.InquiryService/UpdateStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inquiryServiceClient) AddInquiryTimeTable(ctx context.Context, in *InquiryTimeTableModel, opts ...grpc.CallOption) (*InquiryTimeTableId, error) {
	out := new(InquiryTimeTableId)
	err := c.cc.Invoke(ctx, "/genproto.InquiryService/AddInquiryTimeTable", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inquiryServiceClient) GetInquiryTimeTable(ctx context.Context, in *InquiryTimeTableId, opts ...grpc.CallOption) (*InquiryTimeTableModel, error) {
	out := new(InquiryTimeTableModel)
	err := c.cc.Invoke(ctx, "/genproto.InquiryService/GetInquiryTimeTable", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inquiryServiceClient) UpdateInquiryTimeTable(ctx context.Context, in *InquiryTimeTableId, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/genproto.InquiryService/UpdateInquiryTimeTable", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inquiryServiceClient) GetInquiryTimeTables(ctx context.Context, in *GetInquiryTimeTablesRequest, opts ...grpc.CallOption) (*GetInquiryTimeTablesResponse, error) {
	out := new(GetInquiryTimeTablesResponse)
	err := c.cc.Invoke(ctx, "/genproto.InquiryService/GetInquiryTimeTables", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inquiryServiceClient) GetCalendar(ctx context.Context, in *GetCalendarRequest, opts ...grpc.CallOption) (*GetCalendarResponse, error) {
	out := new(GetCalendarResponse)
	err := c.cc.Invoke(ctx, "/genproto.InquiryService/GetCalendar", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inquiryServiceClient) DeleteInquiryTimeTable(ctx context.Context, in *DeleteInquiryTimeTableRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/genproto.InquiryService/DeleteInquiryTimeTable", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InquiryServiceServer is the server API for InquiryService service.
type InquiryServiceServer interface {
	Create(context.Context, *Inquiry) (*InquiryId, error)
	Update(context.Context, *Inquiry) (*InquiryId, error)
	Get(context.Context, *InquiryId) (*Inquiry, error)
	GetAll(context.Context, *GetAllInquiryRequest) (*GetAllInquiryResponse, error)
	Delete(context.Context, *InquiryId) (*emptypb.Empty, error)
	UpdateStatus(context.Context, *StatusNotes) (*emptypb.Empty, error)
	AddInquiryTimeTable(context.Context, *InquiryTimeTableModel) (*InquiryTimeTableId, error)
	GetInquiryTimeTable(context.Context, *InquiryTimeTableId) (*InquiryTimeTableModel, error)
	UpdateInquiryTimeTable(context.Context, *InquiryTimeTableId) (*emptypb.Empty, error)
	GetInquiryTimeTables(context.Context, *GetInquiryTimeTablesRequest) (*GetInquiryTimeTablesResponse, error)
	GetCalendar(context.Context, *GetCalendarRequest) (*GetCalendarResponse, error)
	DeleteInquiryTimeTable(context.Context, *DeleteInquiryTimeTableRequest) (*emptypb.Empty, error)
}

// UnimplementedInquiryServiceServer can be embedded to have forward compatible implementations.
type UnimplementedInquiryServiceServer struct {
}

func (*UnimplementedInquiryServiceServer) Create(context.Context, *Inquiry) (*InquiryId, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedInquiryServiceServer) Update(context.Context, *Inquiry) (*InquiryId, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedInquiryServiceServer) Get(context.Context, *InquiryId) (*Inquiry, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedInquiryServiceServer) GetAll(context.Context, *GetAllInquiryRequest) (*GetAllInquiryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAll not implemented")
}
func (*UnimplementedInquiryServiceServer) Delete(context.Context, *InquiryId) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (*UnimplementedInquiryServiceServer) UpdateStatus(context.Context, *StatusNotes) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateStatus not implemented")
}
func (*UnimplementedInquiryServiceServer) AddInquiryTimeTable(context.Context, *InquiryTimeTableModel) (*InquiryTimeTableId, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddInquiryTimeTable not implemented")
}
func (*UnimplementedInquiryServiceServer) GetInquiryTimeTable(context.Context, *InquiryTimeTableId) (*InquiryTimeTableModel, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInquiryTimeTable not implemented")
}
func (*UnimplementedInquiryServiceServer) UpdateInquiryTimeTable(context.Context, *InquiryTimeTableId) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateInquiryTimeTable not implemented")
}
func (*UnimplementedInquiryServiceServer) GetInquiryTimeTables(context.Context, *GetInquiryTimeTablesRequest) (*GetInquiryTimeTablesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInquiryTimeTables not implemented")
}
func (*UnimplementedInquiryServiceServer) GetCalendar(context.Context, *GetCalendarRequest) (*GetCalendarResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCalendar not implemented")
}
func (*UnimplementedInquiryServiceServer) DeleteInquiryTimeTable(context.Context, *DeleteInquiryTimeTableRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteInquiryTimeTable not implemented")
}

func RegisterInquiryServiceServer(s *grpc.Server, srv InquiryServiceServer) {
	s.RegisterService(&_InquiryService_serviceDesc, srv)
}

func _InquiryService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Inquiry)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InquiryServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/genproto.InquiryService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InquiryServiceServer).Create(ctx, req.(*Inquiry))
	}
	return interceptor(ctx, in, info, handler)
}

func _InquiryService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Inquiry)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InquiryServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/genproto.InquiryService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InquiryServiceServer).Update(ctx, req.(*Inquiry))
	}
	return interceptor(ctx, in, info, handler)
}

func _InquiryService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InquiryId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InquiryServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/genproto.InquiryService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InquiryServiceServer).Get(ctx, req.(*InquiryId))
	}
	return interceptor(ctx, in, info, handler)
}

func _InquiryService_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllInquiryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InquiryServiceServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/genproto.InquiryService/GetAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InquiryServiceServer).GetAll(ctx, req.(*GetAllInquiryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InquiryService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InquiryId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InquiryServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/genproto.InquiryService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InquiryServiceServer).Delete(ctx, req.(*InquiryId))
	}
	return interceptor(ctx, in, info, handler)
}

func _InquiryService_UpdateStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusNotes)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InquiryServiceServer).UpdateStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/genproto.InquiryService/UpdateStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InquiryServiceServer).UpdateStatus(ctx, req.(*StatusNotes))
	}
	return interceptor(ctx, in, info, handler)
}

func _InquiryService_AddInquiryTimeTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InquiryTimeTableModel)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InquiryServiceServer).AddInquiryTimeTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/genproto.InquiryService/AddInquiryTimeTable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InquiryServiceServer).AddInquiryTimeTable(ctx, req.(*InquiryTimeTableModel))
	}
	return interceptor(ctx, in, info, handler)
}

func _InquiryService_GetInquiryTimeTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InquiryTimeTableId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InquiryServiceServer).GetInquiryTimeTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/genproto.InquiryService/GetInquiryTimeTable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InquiryServiceServer).GetInquiryTimeTable(ctx, req.(*InquiryTimeTableId))
	}
	return interceptor(ctx, in, info, handler)
}

func _InquiryService_UpdateInquiryTimeTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InquiryTimeTableId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InquiryServiceServer).UpdateInquiryTimeTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/genproto.InquiryService/UpdateInquiryTimeTable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InquiryServiceServer).UpdateInquiryTimeTable(ctx, req.(*InquiryTimeTableId))
	}
	return interceptor(ctx, in, info, handler)
}

func _InquiryService_GetInquiryTimeTables_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInquiryTimeTablesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InquiryServiceServer).GetInquiryTimeTables(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/genproto.InquiryService/GetInquiryTimeTables",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InquiryServiceServer).GetInquiryTimeTables(ctx, req.(*GetInquiryTimeTablesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InquiryService_GetCalendar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCalendarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InquiryServiceServer).GetCalendar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/genproto.InquiryService/GetCalendar",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InquiryServiceServer).GetCalendar(ctx, req.(*GetCalendarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InquiryService_DeleteInquiryTimeTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteInquiryTimeTableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InquiryServiceServer).DeleteInquiryTimeTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/genproto.InquiryService/DeleteInquiryTimeTable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InquiryServiceServer).DeleteInquiryTimeTable(ctx, req.(*DeleteInquiryTimeTableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _InquiryService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "genproto.InquiryService",
	HandlerType: (*InquiryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _InquiryService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _InquiryService_Update_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _InquiryService_Get_Handler,
		},
		{
			MethodName: "GetAll",
			Handler:    _InquiryService_GetAll_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _InquiryService_Delete_Handler,
		},
		{
			MethodName: "UpdateStatus",
			Handler:    _InquiryService_UpdateStatus_Handler,
		},
		{
			MethodName: "AddInquiryTimeTable",
			Handler:    _InquiryService_AddInquiryTimeTable_Handler,
		},
		{
			MethodName: "GetInquiryTimeTable",
			Handler:    _InquiryService_GetInquiryTimeTable_Handler,
		},
		{
			MethodName: "UpdateInquiryTimeTable",
			Handler:    _InquiryService_UpdateInquiryTimeTable_Handler,
		},
		{
			MethodName: "GetInquiryTimeTables",
			Handler:    _InquiryService_GetInquiryTimeTables_Handler,
		},
		{
			MethodName: "GetCalendar",
			Handler:    _InquiryService_GetCalendar_Handler,
		},
		{
			MethodName: "DeleteInquiryTimeTable",
			Handler:    _InquiryService_DeleteInquiryTimeTable_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "inquiry_service.proto",
}
