// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: respondent_inquiry.proto

package inquiry_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RespondentInquiry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                 string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RespondentId       string  `protobuf:"bytes,2,opt,name=respondent_id,json=respondentId,proto3" json:"respondent_id,omitempty"`
	InquiryId          string  `protobuf:"bytes,3,opt,name=inquiry_id,json=inquiryId,proto3" json:"inquiry_id,omitempty"`
	InquiryTimetableId string  `protobuf:"bytes,4,opt,name=inquiry_timetable_id,json=inquiryTimetableId,proto3" json:"inquiry_timetable_id,omitempty"`
	Link               string  `protobuf:"bytes,5,opt,name=link,proto3" json:"link,omitempty"`
	Note               string  `protobuf:"bytes,6,opt,name=note,proto3" json:"note,omitempty"`
	Rating             float32 `protobuf:"fixed32,7,opt,name=rating,proto3" json:"rating,omitempty"`
	StatusId           string  `protobuf:"bytes,8,opt,name=status_id,json=statusId,proto3" json:"status_id,omitempty"`
}

func (x *RespondentInquiry) Reset() {
	*x = RespondentInquiry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_respondent_inquiry_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespondentInquiry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespondentInquiry) ProtoMessage() {}

func (x *RespondentInquiry) ProtoReflect() protoreflect.Message {
	mi := &file_respondent_inquiry_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespondentInquiry.ProtoReflect.Descriptor instead.
func (*RespondentInquiry) Descriptor() ([]byte, []int) {
	return file_respondent_inquiry_proto_rawDescGZIP(), []int{0}
}

func (x *RespondentInquiry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RespondentInquiry) GetRespondentId() string {
	if x != nil {
		return x.RespondentId
	}
	return ""
}

func (x *RespondentInquiry) GetInquiryId() string {
	if x != nil {
		return x.InquiryId
	}
	return ""
}

func (x *RespondentInquiry) GetInquiryTimetableId() string {
	if x != nil {
		return x.InquiryTimetableId
	}
	return ""
}

func (x *RespondentInquiry) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *RespondentInquiry) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *RespondentInquiry) GetRating() float32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *RespondentInquiry) GetStatusId() string {
	if x != nil {
		return x.StatusId
	}
	return ""
}

type RespondentInquiryId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RespondentInquiryId) Reset() {
	*x = RespondentInquiryId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_respondent_inquiry_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespondentInquiryId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespondentInquiryId) ProtoMessage() {}

func (x *RespondentInquiryId) ProtoReflect() protoreflect.Message {
	mi := &file_respondent_inquiry_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespondentInquiryId.ProtoReflect.Descriptor instead.
func (*RespondentInquiryId) Descriptor() ([]byte, []int) {
	return file_respondent_inquiry_proto_rawDescGZIP(), []int{1}
}

func (x *RespondentInquiryId) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetAllRespondentInquiryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Inquiries []*RespondentInquiry `protobuf:"bytes,1,rep,name=inquiries,proto3" json:"inquiries,omitempty"`
	Count     int32                `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *GetAllRespondentInquiryResponse) Reset() {
	*x = GetAllRespondentInquiryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_respondent_inquiry_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllRespondentInquiryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllRespondentInquiryResponse) ProtoMessage() {}

func (x *GetAllRespondentInquiryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_respondent_inquiry_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllRespondentInquiryResponse.ProtoReflect.Descriptor instead.
func (*GetAllRespondentInquiryResponse) Descriptor() ([]byte, []int) {
	return file_respondent_inquiry_proto_rawDescGZIP(), []int{2}
}

func (x *GetAllRespondentInquiryResponse) GetInquiries() []*RespondentInquiry {
	if x != nil {
		return x.Inquiries
	}
	return nil
}

func (x *GetAllRespondentInquiryResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_respondent_inquiry_proto protoreflect.FileDescriptor

var file_respondent_inquiry_proto_rawDesc = []byte{
	0x0a, 0x18, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x64, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x6e, 0x71,
	0x75, 0x69, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x67, 0x65, 0x6e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xf6, 0x01, 0x0a, 0x11, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x64,
	0x65, 0x6e, 0x74, 0x49, 0x6e, 0x71, 0x75, 0x69, 0x72, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x64, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x64, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12,
	0x1d, 0x0a, 0x0a, 0x69, 0x6e, 0x71, 0x75, 0x69, 0x72, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x6e, 0x71, 0x75, 0x69, 0x72, 0x79, 0x49, 0x64, 0x12, 0x30,
	0x0a, 0x14, 0x69, 0x6e, 0x71, 0x75, 0x69, 0x72, 0x79, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x74, 0x61,
	0x62, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x69, 0x6e,
	0x71, 0x75, 0x69, 0x72, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6c, 0x69, 0x6e, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x6f, 0x74, 0x65, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x61, 0x74, 0x69,
	0x6e, 0x67, 0x18, 0x07, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67,
	0x12, 0x1b, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x69, 0x64, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x49, 0x64, 0x22, 0x25, 0x0a,
	0x13, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x64, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x71, 0x75, 0x69,
	0x72, 0x79, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x72, 0x0a, 0x1f, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x64, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x71, 0x75, 0x69, 0x72, 0x79, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x39, 0x0a, 0x09, 0x69, 0x6e, 0x71, 0x75, 0x69,
	0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x67, 0x65, 0x6e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x64, 0x65, 0x6e, 0x74,
	0x49, 0x6e, 0x71, 0x75, 0x69, 0x72, 0x79, 0x52, 0x09, 0x69, 0x6e, 0x71, 0x75, 0x69, 0x72, 0x69,
	0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0x1a, 0x5a, 0x18, 0x67, 0x65, 0x6e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x69, 0x6e, 0x71, 0x75, 0x69, 0x72, 0x79, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_respondent_inquiry_proto_rawDescOnce sync.Once
	file_respondent_inquiry_proto_rawDescData = file_respondent_inquiry_proto_rawDesc
)

func file_respondent_inquiry_proto_rawDescGZIP() []byte {
	file_respondent_inquiry_proto_rawDescOnce.Do(func() {
		file_respondent_inquiry_proto_rawDescData = protoimpl.X.CompressGZIP(file_respondent_inquiry_proto_rawDescData)
	})
	return file_respondent_inquiry_proto_rawDescData
}

var file_respondent_inquiry_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_respondent_inquiry_proto_goTypes = []interface{}{
	(*RespondentInquiry)(nil),               // 0: genproto.RespondentInquiry
	(*RespondentInquiryId)(nil),             // 1: genproto.RespondentInquiryId
	(*GetAllRespondentInquiryResponse)(nil), // 2: genproto.GetAllRespondentInquiryResponse
}
var file_respondent_inquiry_proto_depIdxs = []int32{
	0, // 0: genproto.GetAllRespondentInquiryResponse.inquiries:type_name -> genproto.RespondentInquiry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_respondent_inquiry_proto_init() }
func file_respondent_inquiry_proto_init() {
	if File_respondent_inquiry_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_respondent_inquiry_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespondentInquiry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_respondent_inquiry_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespondentInquiryId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_respondent_inquiry_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllRespondentInquiryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_respondent_inquiry_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_respondent_inquiry_proto_goTypes,
		DependencyIndexes: file_respondent_inquiry_proto_depIdxs,
		MessageInfos:      file_respondent_inquiry_proto_msgTypes,
	}.Build()
	File_respondent_inquiry_proto = out.File
	file_respondent_inquiry_proto_rawDesc = nil
	file_respondent_inquiry_proto_goTypes = nil
	file_respondent_inquiry_proto_depIdxs = nil
}
